return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    spec = {
      { "<leader>c", group = "code" },
      { "<leader>cc", ":SlimeConfig<cr>", desc = "slime config" },
      { "<leader>cn", ":split term://$SHELL<cr>", desc = "new terminal" },
      { "<leader>co", ":Gen<cr>", desc = "Ollama" },
      { "<leader>d", group = "Test/Debug" },
      { "<leader>f", group = "Find/search" },
      { "<leader>fc", "<cmd>Telescope git_commits<cr>", desc = "git commits" },
      { "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "files" },
      { "<leader>fg", "<cmd>Telescope live_grep<cr>", desc = "grep" },
      { "<leader>fh", "<cmd>Telescope help_tags<cr>", desc = "help" },
      { "<leader>fj", "<cmd>Telescope jumplist<cr>", desc = "jumplist" },
      { "<leader>fk", "<cmd>Telescope keymaps<cr>", desc = "keymaps" },
      { "<leader>fl", "<cmd>Telescope loclist<cr>", desc = "loclist" },
      { "<leader>fq", "<cmd>Telescope quickfix<cr>", desc = "quickfix" },
      { "<leader>fr", "<cmd>Telescope lsp_references<cr>", desc = "references" },
      { "<leader>fw", "<cmd>Telescope file_browser<cr>", desc = "File browser" },
      { "<leader>g", group = "Git" },
      { "<leader>gc", "<cmd>Neogit commit<cr>", desc = "commit" },
      { "<leader>gg", "<cmd>Neogit<cr>", desc = "neogit" },
      { "<leader>l", group = "LSP" },
      { "<leader>o", group = "Obsidian" },
      { "<leader>oa", "<cmd>Obsidian tags<cr>", desc = "tags" },
      { "<leader>ob", "<cmd>Obsidian backlinks<cr>", desc = "backlinks" },
      { "<leader>od", "<cmd>Obsidian toggle_checkbox<cr>", desc = "toggle checkbox" },
      { "<leader>oe", "<cmd>Obsidian extract_note<cr>", desc = "extract note" },
      { "<leader>of", "<cmd>Obsidian follow_link<cr>", desc = "follow link" },
      { "<leader>ol", "<cmd>Obsidian link<cr>", desc = "create link to note" },
      { "<leader>oL", "<cmd>Obsidian link_new<cr>", desc = "create new link" },
      { "<leader>on", "<cmd>Obsidian new<cr>", desc = "new note" },
      { "<leader>oo", "<cmd>Obsidian quick_switch<cr>", desc = "quick switch" },
      { "<leader>op", "<cmd>Obsidian paste_img<cr>", desc = "Paste image" },
      { "<leader>or", "<cmd>Obsidian rename<cr>", desc = "Rename" },
      { "<leader>os", "<cmd>Obsidian search<cr>", desc = "search" },
      { "<leader>ot", "<cmd>Obsidian template<cr>", desc = "insert template" },
      { "<leader>oT", "<cmd>Obsidian new_from_template<cr>", desc = "New from template" },
      { "<leader>ow", "<cmd>Obsidian workspace<cr>", desc = "Change workspace" },
      { "<leader>q", group = "Quarto" },
      { "<leader>s", group = "Spell" },
      { "<leader>sb", "zw", desc = "bad" },
      { "<leader>sg", "zg", desc = "good" },
      { "<leader>sn", "]s", desc = "next" },
      { "<leader>sp", "[s", desc = "previous" },
      { "<leader>sr", "zg", desc = "right" },
      { "<leader>ss", "<cmd>Telescope spell_suggest<cr>", desc = "spelling" },
      { "<leader>sw", "zw", desc = "wrong" },
      { "<leader>sl", "[s1z=`]", desc = "[S]pell fix [L]ast" },
      { "<leader>t", group = "Todo" },
      { "<leader>w", group = "Workspace" },
      { "<leader>x", "<cmd>bd<cr>", desc = "close buffer" },
    },
  },
  -- spelling = {
  --     enabled = true, -- enabling this will show WhichKey when pressing z= to select spelling suggestions
  --     suggestions = 20, -- how many suggestions should be shown in the list?
  -- },
}
-- vim: ts=2 sts=2 sw=2 et
